### ISSUE TITLE
Unobtainium page does not load content

### ISSUE THREAD

**Issue by GeorgeWL** [ineffyble/genders.wtf#123]
https://genders.wtf/unobtainium/ leads to a blank page with no content other than the standard header and footer

**Comment by GeorgeWL** [comment]
https://github.com/ineffyble/genders.wtf/assets/5931248/1f674b6a-450e-4b6d-aedd-ce416160493a

Recording

**Comment by ineffyble** [comment]
Very amused that out of all the genders this could happen to, it was the one named "Unobtanium".

**Comment by ineffyble** [comment]
Fixed, the URL is now https://genders.wtf/gender/unobtainium/ and shows correctly.
