### ISSUE TITLE
Wrong content-type

### ISSUE THREAD

**Issue by ScoreUnder** [ineffyble/genders.wtf#21]
The content-type for https://genders.wtf/select-a-g%5Bscreaming%5D is text/plain, which causes it to render as plain text on compliant browsers including Firefox.

```
score@kirisame ~ % curl -Ig 'https://genders.wtf/select-a-g%5Bscreaming%5D'  
HTTP/2 200 
accept-ranges: bytes
age: 0
cache-control: public, max-age=0, must-revalidate
content-type: text/plain; charset=UTF-8
date: Mon, 19 Dec 2022 02:44:58 GMT
etag: "6180213f686150bc59edde95a35eaeb2-ssl"
server: Netlify
strict-transport-security: max-age=31536000
x-nf-request-id: 01GMM4A9VPFY1F78HGY2HP5TWH
content-length: 6482
```

**Comment by ineffyble** [comment]
Whoops, this was introduced when that URL got tweaked due to being invalid in other ways. I've removed the [] from it now, so that URL will no longer work but https://genders.wtf/select-a-g-screaming should be working instead in ~1 min.
